@TodoApi_HostAddress = http://localhost:5007

### Get all todos
GET {{TodoApi_HostAddress}}z  
Accept: application/json

###

### Get todo by id
@todoId = 00000000-0000-0000-0000-000000000001
GET {{TodoApi_HostAddress}}/api/v2/Todos/{{todoId}}
Accept: application/json

###

### Create todo
POST {{TodoApi_HostAddress}}/api/v2/Todos
Content-Type: application/json

{
  "title": "New todo item"
}

###

### Update todo
PUT {{TodoApi_HostAddress}}/api/v2/Todos/{{todoId}}
Content-Type: application/json

{
  "title": "Updated todo item",
  "isCompleted": true
}

###

### Delete todo
DELETE {{TodoApi_HostAddress}}/api/v2/Todos/{{todoId}}

###
